export const nftworks = [
  {
    id: "zw",
    name: "Z.W.",
    logo: require("../../assets/images/ZW/logo.png"),
    avatar: require("../../assets/images/ZW/avatar.png"),
    title: "message.artist.nftworks.zw.title",
    des: "message.artist.nftworks.zw.des",
    works: [
      { logo: require("../../assets/images/ZW/A.webp"), name: "message.artist.nftworks.zw.works[0].name" },
      { logo: require("../../assets/images/ZW/Akemi_Homura.webp"), name: "message.artist.nftworks.zw.works[1].name" },
      { logo: require("../../assets/images/ZW/Card_game.webp"), name: "message.artist.nftworks.zw.works[2].name" },
      { logo: require("../../assets/images/ZW/Joker.webp"), name: "message.artist.nftworks.zw.works[3].name" },
      { logo: require("../../assets/images/ZW/Kaguya_sama.webp"), name: "message.artist.nftworks.zw.works[4].name" },
      { logo: require("../../assets/images/ZW/Kanna.webp"), name: "message.artist.nftworks.zw.works[5].name" },
      { logo: require("../../assets/images/ZW/Kuro.webp"), name: "message.artist.nftworks.zw.works[6].name" },
      { logo: require("../../assets/images/ZW/Makia.webp"), name: "message.artist.nftworks.zw.works[7].name" },
      { logo: require("../../assets/images/ZW/Misa.webp"), name: "message.artist.nftworks.zw.works[8].name" },
      { logo: require("../../assets/images/ZW/Noshiro.webp"), name: "message.artist.nftworks.zw.works[9].name" },
      { logo: require("../../assets/images/ZW/Satono_Diamond.webp"), name: "message.artist.nftworks.zw.works[10].name" },
      { logo: require("../../assets/images/ZW/Tomoyo_Daidoji.webp"), name: "message.artist.nftworks.zw.works[11].name" },
    ],
  },
  {
    id: "akiha",
    name: "Akiha",
    logo: require("../../assets/images/Akiha/logo.png"),
    avatar: require("../../assets/images/Akiha/avatar.png"),
    title: "message.artist.nftworks.akiha.title",
    des: "message.artist.nftworks.akiha.des",
    works: [
      { logo: require("../../assets/images/Akiha/Armed_girl.webp"), name: "message.artist.nftworks.akiha.works[0].name" },
      { logo: require("../../assets/images/Akiha/Crying_in_the_gym.webp"), name: "message.artist.nftworks.akiha.works[1].name" },
      { logo: require("../../assets/images/Akiha/Fall.webp"), name: "message.artist.nftworks.akiha.works[2].name" },
      { logo: require("../../assets/images/Akiha/Windy.webp"), name: "message.artist.nftworks.akiha.works[3].name" },
      { logo: require("../../assets/images/Akiha/After_jogging.webp"), name: "message.artist.nftworks.akiha.works[4].name" },
      { logo: require("../../assets/images/Akiha/Summer.webp"), name: "message.artist.nftworks.akiha.works[5].name" },
      { logo: require("../../assets/images/Akiha/Shadow.webp"), name: "message.artist.nftworks.akiha.works[6].name" },
      { logo: require("../../assets/images/Akiha/X.webp"), name: "message.artist.nftworks.akiha.works[7].name" },
      { logo: require("../../assets/images/Akiha/Witch.webp"), name: "message.artist.nftworks.akiha.works[8].name" },
      { logo: require("../../assets/images/Akiha/White_hair_angel.webp"), name: "message.artist.nftworks.akiha.works[9].name" },
      { logo: require("../../assets/images/Akiha/The_happy_ending_of_a_dying_girl.webp"), name: "message.artist.nftworks.akiha.works[10].name" },
      { logo: require("../../assets/images/Akiha/Encountered_and_got_knocked_down.webp"), name: "message.artist.nftworks.akiha.works[11].name" },
    ],
  },
  {
    id: "negoro",
    name: "Negoro",
    logo: require("../../assets/images/Negoro/logo.png"),
    avatar: require("../../assets/images/Negoro/avatar.png"),
    title: "message.artist.nftworks.negoro.title",
    des: "message.artist.nftworks.negoro.des",
    works: [
      { logo: require("../../assets/images/Negoro/The_duel.webp"), name: "message.artist.nftworks.negoro.works[0].name" },
      { logo: require("../../assets/images/Negoro/Irelia.webp"), name: "message.artist.nftworks.negoro.works[1].name" },
      { logo: require("../../assets/images/Negoro/Ishtar.webp"), name: "message.artist.nftworks.negoro.works[2].name" },
      { logo: require("../../assets/images/Negoro/Luna.webp"), name: "message.artist.nftworks.negoro.works[3].name" },
      { logo: require("../../assets/images/Negoro/Lucia.webp"), name: "message.artist.nftworks.negoro.works[4].name" },
      { logo: require("../../assets/images/Negoro/Nezuko.webp"), name: "message.artist.nftworks.negoro.works[5].name" },
      { logo: require("../../assets/images/Negoro/Yor.webp"), name: "message.artist.nftworks.negoro.works[6].name" },
      { logo: require("../../assets/images/Negoro/Princess_knight.webp"), name: "message.artist.nftworks.negoro.works[7].name" },
      { logo: require("../../assets/images/Negoro/Rose.webp"), name: "message.artist.nftworks.negoro.works[8].name" },
      { logo: require("../../assets/images/Negoro/Kamisato_Ayaka.webp"), name: "message.artist.nftworks.negoro.works[9].name" },
      { logo: require("../../assets/images/Negoro/Okita_Sōji.webp"), name: "message.artist.nftworks.negoro.works[10].name" },
      { logo: require("../../assets/images/Negoro/Kaedehara_Kazuha.webp"), name: "message.artist.nftworks.negoro.works[11].name" },
    ],
  },
  {
    // logo 作品集大图
    // avatar 画师头像
    // title 作品集标题
    // name 画师名字
    // des 画师描述
    id: "shikastudio",
    name: "Shika studio",
    logo: require("../../assets/images/ShikaStudio/logo.png"),
    avatar: require("../../assets/images/ShikaStudio/avatar.png"),
    title: "message.artist.nftworks.shikastudio.title",
    des: "message.artist.nftworks.shikastudio.des",
    works: [
      // logo 卡牌大头贴
      // name 卡牌名称
      // card 卡牌图
      // card2 卡牌背景图
      // attribute 属性
      // level 等级
      // starlevel 星级
      // rarity 稀有度
      // worddes 作品介绍
      // nftdes NFT介绍
      {
        logo: require("../../assets/images/ShikaStudio/Lord.png"),
        card: require("../../assets/images/ShikaStudio/Lord-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Lord-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Lord.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[0].name",
        attribute: "message.artist.nftworks.shikastudio.works[0].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[0].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[0].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Katarina.webp"),
        card: require("../../assets/images/ShikaStudio/Katarina-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Katarina-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Katarina.mp4"),
        rarity: "R",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[1].name",
        attribute: "message.artist.nftworks.shikastudio.works[1].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[1].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[1].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Mia.png"),
        card: require("../../assets/images/ShikaStudio/Mia-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Mia-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Mia.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[2].name",
        attribute: "message.artist.nftworks.shikastudio.works[2].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[2].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[2].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Una.png"),
        card: require("../../assets/images/ShikaStudio/Una-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Una-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Una.mp4"),
        rarity: "SR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[3].name",
        attribute: "message.artist.nftworks.shikastudio.works[3].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[3].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[3].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Rin.png"),
        card: require("../../assets/images/ShikaStudio/Rin-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Rin-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Rin.mp4"),
        rarity: "SR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[4].name",
        attribute: "message.artist.nftworks.shikastudio.works[4].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[4].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[4].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Ichika.png"),
        card: require("../../assets/images/ShikaStudio/Ichika-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Ichika-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Ichika.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[5].name",
        attribute: "message.artist.nftworks.shikastudio.works[5].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[5].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[5].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Asuka.webp"),
        card: require("../../assets/images/ShikaStudio/Asuka-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Asuka-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Asuka.mp4"),
        rarity: "R",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[6].name",
        attribute: "message.artist.nftworks.shikastudio.works[6].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[6].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[6].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Rika.png"),
        card: require("../../assets/images/ShikaStudio/Rika-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Rika-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Rika.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[7].name",
        attribute: "message.artist.nftworks.shikastudio.works[7].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[7].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[7].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Kasey.png"),
        card: require("../../assets/images/ShikaStudio/Kasey-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Kasey-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Kasey.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[8].name",
        attribute: "message.artist.nftworks.shikastudio.works[8].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[8].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[8].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Maki.png"),
        card: require("../../assets/images/ShikaStudio/Maki-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Maki-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Maki.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[9].name",
        attribute: "message.artist.nftworks.shikastudio.works[9].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[9].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[9].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Shino.png"),
        card: require("../../assets/images/ShikaStudio/Shino-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Shino-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Shino.mp4"),
        rarity: "SR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[10].name",
        attribute: "message.artist.nftworks.shikastudio.works[10].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[10].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[10].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Tina.png"),
        card: require("../../assets/images/ShikaStudio/Tina-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Tina-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Tina.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[11].name",
        attribute: "message.artist.nftworks.shikastudio.works[11].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[11].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[11].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Carol.webp"),
        card: require("../../assets/images/ShikaStudio/Carol-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Carol-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Carol.mp4"),
        rarity: "R",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[12].name",
        attribute: "message.artist.nftworks.shikastudio.works[12].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[12].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[12].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Kate.png"),
        card: require("../../assets/images/ShikaStudio/Kate-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Kate-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Kate.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[13].name",
        attribute: "message.artist.nftworks.shikastudio.works[13].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[13].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[13].nftdes",
      },
      {
        logo: require("../../assets/images/ShikaStudio/Alice.png"),
        card: require("../../assets/images/ShikaStudio/Alice-1.webp"),
        card2: require("../../assets/images/ShikaStudio/Alice-2.webp"),
        video: require("../../assets/videos/ShikaStudio/Alice.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks.shikastudio.level",
        starlevel: "message.artist.nftworks.shikastudio.starlevel",
        name: "message.artist.nftworks.shikastudio.works[14].name",
        attribute: "message.artist.nftworks.shikastudio.works[14].attribute",
        worddes: "message.artist.nftworks.shikastudio.works[14].worddes",
        nftdes: "message.artist.nftworks.shikastudio.works[14].nftdes",
      },
    ],
  },
];
