export const nftworks = [
  {
    id: "zw",
    name: "Z.W.",
    logo: require("../../assets/images/artist/zw/logo.png"),
    avatar: require("../../assets/images/artist/zw/avatar.png"),
    title: "message.artist.nftworks[0].title",
    des: "message.artist.nftworks[0].des",
    works: [
      { logo: require("../../assets/images/artist/zw/1.jpg") },
      { logo: require("../../assets/images/artist/zw/2.jpg") },
      { logo: require("../../assets/images/artist/zw/3.jpg") },
      { logo: require("../../assets/images/artist/zw/4.jpg") },
      { logo: require("../../assets/images/artist/zw/5.jpg") },
      { logo: require("../../assets/images/artist/zw/6.jpg") },
      { logo: require("../../assets/images/artist/zw/7.jpg") },
      { logo: require("../../assets/images/artist/zw/8.jpg") },
      { logo: require("../../assets/images/artist/zw/9.jpg") },
      { logo: require("../../assets/images/artist/zw/10.jpg") },
      { logo: require("../../assets/images/artist/zw/11.jpg") },
      { logo: require("../../assets/images/artist/zw/12.jpg") },
    ],
  },
  {
    id: "akiha",
    name: "Akiha",
    logo: require("../../assets/images/artist/akiha/logo.png"),
    avatar: require("../../assets/images/artist/akiha/avatar.png"),
    title: "message.artist.nftworks[1].title",
    des: "message.artist.nftworks[1].des",
    works: [
      { logo: require("../../assets/images/artist/akiha/1.jpg") },
      { logo: require("../../assets/images/artist/akiha/2.jpg") },
      { logo: require("../../assets/images/artist/akiha/3.jpg") },
      { logo: require("../../assets/images/artist/akiha/4.jpg") },
      { logo: require("../../assets/images/artist/akiha/5.jpg") },
      { logo: require("../../assets/images/artist/akiha/6.jpg") },
      { logo: require("../../assets/images/artist/akiha/7.jpg") },
      { logo: require("../../assets/images/artist/akiha/8.jpg") },
      { logo: require("../../assets/images/artist/akiha/9.jpg") },
      { logo: require("../../assets/images/artist/akiha/10.jpg") },
      { logo: require("../../assets/images/artist/akiha/11.jpg") },
      { logo: require("../../assets/images/artist/akiha/12.jpg") },
    ],
  },
  {
    id: "negoro",
    name: "Negoro",
    logo: require("../../assets/images/artist/negoro/logo.png"),
    avatar: require("../../assets/images/artist/negoro/avatar.png"),
    title: "message.artist.nftworks[2].title",
    des: "message.artist.nftworks[2].des",
    works: [
      { logo: require("../../assets/images/artist/negoro/1.jpg") },
      { logo: require("../../assets/images/artist/negoro/2.jpg") },
      { logo: require("../../assets/images/artist/negoro/3.jpg") },
      { logo: require("../../assets/images/artist/negoro/4.jpg") },
      { logo: require("../../assets/images/artist/negoro/5.jpg") },
      { logo: require("../../assets/images/artist/negoro/6.jpg") },
      { logo: require("../../assets/images/artist/negoro/7.jpg") },
      { logo: require("../../assets/images/artist/negoro/8.jpg") },
      { logo: require("../../assets/images/artist/negoro/9.jpg") },
      { logo: require("../../assets/images/artist/negoro/10.jpg") },
      { logo: require("../../assets/images/artist/negoro/11.jpg") },
      { logo: require("../../assets/images/artist/negoro/12.jpg") },
    ],
  },
  {
    // logo 作品集大图
    // avatar 画师头像
    // title 作品集标题
    // name 画师名字
    // des 画师描述
    id: "shikastudio",
    name: "Shika studio",
    logo: require("../../assets/images/artist/shikastudio/logo.png"),
    avatar: require("../../assets/images/artist/shikastudio/avatar.png"),
    title: "message.artist.nftworks[3].title",
    des: "message.artist.nftworks[3].des",
    works: [
      // logo 卡牌大头贴
      // name 卡牌名称
      // card 卡牌图
      // card2 卡牌背景图
      // attribute 属性
      // level 等级
      // starlevel 星级
      // rarity 稀有度
      // worddes 作品介绍
      // nftdes NFT介绍
      {
        logo: require("../../assets/images/artist/shikastudio/Lord.png"),
        card: require("../../assets/images/artist/shikastudio/Lord-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Lord-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Lord.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[0].name",
        attribute: "message.artist.nftworks[3].works[0].attribute",
        worddes: "message.artist.nftworks[3].works[0].worddes",
        nftdes: "message.artist.nftworks[3].works[0].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Katarina.webp"),
        card: require("../../assets/images/artist/shikastudio/Katarina-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Katarina-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Katarina.mp4"),
        rarity: "R",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[1].name",
        attribute: "message.artist.nftworks[3].works[1].attribute",
        worddes: "message.artist.nftworks[3].works[1].worddes",
        nftdes: "message.artist.nftworks[3].works[1].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Mia.png"),
        card: require("../../assets/images/artist/shikastudio/Mia-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Mia-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Mia.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[2].name",
        attribute: "message.artist.nftworks[3].works[2].attribute",
        worddes: "message.artist.nftworks[3].works[2].worddes",
        nftdes: "message.artist.nftworks[3].works[2].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Una.png"),
        card: require("../../assets/images/artist/shikastudio/Una-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Una-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Una.mp4"),
        rarity: "SR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[3].name",
        attribute: "message.artist.nftworks[3].works[3].attribute",
        worddes: "message.artist.nftworks[3].works[3].worddes",
        nftdes: "message.artist.nftworks[3].works[3].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Rin.png"),
        card: require("../../assets/images/artist/shikastudio/Rin-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Rin-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Rin.mp4"),
        rarity: "SR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[4].name",
        attribute: "message.artist.nftworks[3].works[4].attribute",
        worddes: "message.artist.nftworks[3].works[4].worddes",
        nftdes: "message.artist.nftworks[3].works[4].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Ichika.png"),
        card: require("../../assets/images/artist/shikastudio/Ichika-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Ichika-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Ichika.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[5].name",
        attribute: "message.artist.nftworks[3].works[5].attribute",
        worddes: "message.artist.nftworks[3].works[5].worddes",
        nftdes: "message.artist.nftworks[3].works[5].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Asuka.webp"),
        card: require("../../assets/images/artist/shikastudio/Asuka-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Asuka-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Asuka.mp4"),
        rarity: "R",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[6].name",
        attribute: "message.artist.nftworks[3].works[6].attribute",
        worddes: "message.artist.nftworks[3].works[6].worddes",
        nftdes: "message.artist.nftworks[3].works[6].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Rika.png"),
        card: require("../../assets/images/artist/shikastudio/Rika-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Rika-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Rika.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[7].name",
        attribute: "message.artist.nftworks[3].works[7].attribute",
        worddes: "message.artist.nftworks[3].works[7].worddes",
        nftdes: "message.artist.nftworks[3].works[7].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Kasey.png"),
        card: require("../../assets/images/artist/shikastudio/Kasey-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Kasey-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Kasey.mp4"),
        rarity: "MR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[8].name",
        attribute: "message.artist.nftworks[3].works[8].attribute",
        worddes: "message.artist.nftworks[3].works[8].worddes",
        nftdes: "message.artist.nftworks[3].works[8].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Maki.png"),
        card: require("../../assets/images/artist/shikastudio/Maki-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Maki-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Maki.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[9].name",
        attribute: "message.artist.nftworks[3].works[9].attribute",
        worddes: "message.artist.nftworks[3].works[9].worddes",
        nftdes: "message.artist.nftworks[3].works[9].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Shino.png"),
        card: require("../../assets/images/artist/shikastudio/Shino-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Shino-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Shino.mp4"),
        rarity: "SR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[10].name",
        attribute: "message.artist.nftworks[3].works[10].attribute",
        worddes: "message.artist.nftworks[3].works[10].worddes",
        nftdes: "message.artist.nftworks[3].works[10].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Tina.png"),
        card: require("../../assets/images/artist/shikastudio/Tina-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Tina-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Tina.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[11].name",
        attribute: "message.artist.nftworks[3].works[11].attribute",
        worddes: "message.artist.nftworks[3].works[11].worddes",
        nftdes: "message.artist.nftworks[3].works[11].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Carol.webp"),
        card: require("../../assets/images/artist/shikastudio/Carol-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Carol-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Carol.mp4"),
        rarity: "R",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[12].name",
        attribute: "message.artist.nftworks[3].works[12].attribute",
        worddes: "message.artist.nftworks[3].works[12].worddes",
        nftdes: "message.artist.nftworks[3].works[12].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Kate.png"),
        card: require("../../assets/images/artist/shikastudio/Kate-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Kate-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Kate.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[13].name",
        attribute: "message.artist.nftworks[3].works[13].attribute",
        worddes: "message.artist.nftworks[3].works[13].worddes",
        nftdes: "message.artist.nftworks[3].works[13].nftdes",
      },
      {
        logo: require("../../assets/images/artist/shikastudio/Alice.png"),
        card: require("../../assets/images/artist/shikastudio/Alice-1.webp"),
        card2: require("../../assets/images/artist/shikastudio/Alice-2.webp"),
        video: require("../../assets/videos/artist/shikastudio/Alice.mp4"),
        rarity: "UR",
        level: "message.artist.nftworks[3].level",
        starlevel: "message.artist.nftworks[3].starlevel",
        name: "message.artist.nftworks[3].works[14].name",
        attribute: "message.artist.nftworks[3].works[14].attribute",
        worddes: "message.artist.nftworks[3].works[14].worddes",
        nftdes: "message.artist.nftworks[3].works[14].nftdes",
      },
    ],
  },
];
